sudo: false

language: java
jdk:
  - oraclejdk7

cache:
    directories:
        - $HOME/.m2
        - $HOME/apache-maven-3.3.9

before_script:
    - mkdir ~/bin
    - wget -O ~/bin/mvn https://raw.githubusercontent.com/yregaieg/maven-config-script/master/scripts/mvn.sh
    - chmod +x ~/bin/mvn
    - echo "MAVEN_OPTS='-Xmx2g -XX:MaxPermSize=512m'" > ~/.mavenrc
    - echo "PATH=~/bin:$PATH" >> ~/.bashrc


script:
    - rm -rf $HOME/.m2/repository/org/alfresco/surf/
    - cd surf
    - mvn clean install
    - rm -rf $HOME/.m2/repository/org/alfresco/surf/
